# Generated by Django 5.1.6 on 2025-02-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="consumation_average_days",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="items",
            name="department",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="items",
            name="is_edible",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
