# Generated by Django 5.1.7 on 2025-03-28 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item_macronutriments", "0002_itemmacronutriments_description"),
        ("items", "0002_alter_items_consumation_average_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="macronutriments",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="item_macronutriments.itemmacronutriments",
                verbose_name="macronutriments",
            ),
        ),
    ]
