# Generated by Django 5.1.7 on 2025-04-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_items_macronutriments"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="emoji",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
