# Generated by Django 5.1.6 on 2025-02-26 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("items", "0003_items_macronutriments"),
        ("shopping_list", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingListItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_checked", models.BooleanField()),
                ("is_proposed", models.BooleanField()),
                ("quantity", models.IntegerField()),
                ("weight", models.FloatField(blank=True, null=True)),
                (
                    "unit_weight",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("volume", models.FloatField(blank=True, null=True)),
                (
                    "unit_volume",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="items.items",
                        verbose_name="user",
                    ),
                ),
                (
                    "shopping_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shopping_list.shoppinglist",
                        verbose_name="shopping list",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "db_table": "shopping_list_item",
            },
        ),
    ]
