# Generated by Django 5.1.6 on 2025-02-26 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_list_items", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="shoppinglistitems",
            table="shopping_list_items",
        ),
    ]
