# Generated by Django 5.1.6 on 2025-02-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_list_items", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppinglistitems",
            name="unit_volume",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="shoppinglistitems",
            name="unit_weight",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="shoppinglistitems",
            name="volume",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shoppinglistitems",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
