# Generated by Django 5.1.6 on 2025-02-06 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_preferences", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userpreferences",
            old_name="user_id",
            new_name="user",
        ),
    ]
