# Generated by Django 5.1.6 on 2025-02-07 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_preferences", "0002_rename_user_id_userpreferences_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userpreferences",
            old_name="preferenceType",
            new_name="preference_type",
        ),
    ]
