# Generated by Django 5.1.6 on 2025-02-07 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_preferences",
            "0003_rename_preferencetype_userpreferences_preference_type",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="userpreferences",
            table="user_preferences",
        ),
    ]
