# Generated by Django 5.1.6 on 2025-02-26 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_list", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="shoppinglist",
            table="shopping_lists",
        ),
    ]
