# Generated by Django 5.1.6 on 2025-02-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item_macronutriments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemmacronutriments",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
