# Generated by Django 5.1.6 on 2025-02-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item_categories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemcategories",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
