# Generated by Django 5.1.7 on 2025-03-28 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0001_initial"),
        ("shopping_list", "0002_alter_shoppinglist_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="shopping_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shopping_list.shoppinglist",
                verbose_name="shopping_list",
            ),
        ),
    ]
